version: "3.0"

services:
  benchmark:
    env_file:
      - ".docker-compose-env"
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    command: ["/usr/bin/env", "python3", "./code_ssnp/experiment1_direct.py", "--mode", "tfidf", "--n_jobs", "20", "--optimization", "random", "--random_permutations", "100"]
    volumes:
      - ./data/:/data
      - /workspace/DimensionReduction/code_ssnp/results_direct/:/results_direct
      - /tmp/:/tmp
    deploy:
      resources:
        limits:
          cpus: '20'
